<%include file="../header.html"/>


<h1 class="fancy">${name}</h1>
<div class="span-12">

<fieldset>
    <legend>return values<legend>
% if code != UNDEFINED:
 <p> <label>Code returned is:</label> ${code} </p>
% endif

% if consumer_key != UNDEFINED:
  <p><label>Consumer Key used:</label>  ${consumer_key} </p>
% endif

% if state != UNDEFINED:
 <p>State :  ${state} </p>
% endif
</fieldset>

<p> user agent grants expects</p>

<p>
 access_token
         REQUIRED.  The access token issued by the authorization server.
   token_type
         REQUIRED.  The type of the token issued as described in
         Section 7.1.  Value is case insensitive.
   expires_in
         OPTIONAL.  The duration in seconds of the access token
         lifetime.  For example, the value "3600" denotes that the
         access token will expire in one hour from the time the response
         was generated.
   refresh_token
         OPTIONAL.  The refresh token which can be used to obtain new
         access tokens using the same authorization grant as described
         in Section 6.
   scope
         OPTIONAL.  The scope of the access request expressed as a list
         of space-delimited, case sensitive strings.  The value is
         defined by the authorization server.  If the value contains
         multiple space-delimited strings, their order does not matter,
         and each string adds an additional access range to the
         requested scope.  The authorization server SHOULD include the
         parameter if the requested scope is different from the one
         requested by the client.

// spec confusion:

   state
         REQUIRED if the "state" parameter was present in the client
         authorization request.  Set to the exact value received from
         the client.

   access_token_secret
         REQUIRED if requested by the client.  The corresponding access
         token secret as requested by the client.
</p>

<p> web server grant expects</p>
<p>
   code
         REQUIRED.  The verification code generated by the authorization
         server.

   state
         REQUIRED if the "state" parameter was present in the client
         authorization request.  Set to the exact value received from
         the client.
</p>

<p> user agent/ web server denies expects</p>
<p>
 error
         REQUIRED.  The parameter value MUST be set to "user_denied".

   state
         REQUIRED if the "state" parameter was present in the client
         authorization request.  Set to the exact value received from
         the client.

error
         REQUIRED.  A single error code from the following:
         invalid_request
               The request is missing a required parameter, includes an
               unsupported parameter or parameter value, repeats a
               parameter, includes multiple credentials, utilizes more
               than one mechanism for authenticating the client, or is
               otherwise malformed.
         invalid_client
               Client authentication failed (e.g. unknown client, no
               client credentials included, multiple client credentials
               included, or unsupported credentials type).  The
               authorization server MAY return an HTTP 401
               (Unauthorized) status code to indicate which HTTP
               authentication schemes are supported.  If the client
               attempted to authenticate via the "Authorization" request
               header field, the authorization server MUST respond with
               an HTTP 401 (Unauthorized) status code, and include the
               "WWW-Authenticate" response header field matching the
               authentication scheme used by the client.



         invalid_grant
               The provided authorization grant is invalid, expired,
               revoked, does not match the redirection URI used in the
               authorization request, or was issued to another client.
         unauthorized_client
               The authenticated client is not authorized to use this
               authorization grant type.
         unsupported_grant_type
               The authorization grant type is not supported by the
               authorization server.
         invalid_scope
               The requested scope is invalid, unknown, malformed, or
               exceeds the scope granted by the resource owner.
   error_description
         OPTIONAL.  A human-readable text providing additional
         information, used to assist in the understanding and resolution
         of the error occurred.
   error_uri
         OPTIONAL.  A URI identifying a human-readable web page with
         information about the error, used to provide the resource owner
         with additional information about the error.

</p>
</div>


<%include file="../footer.html"/>
